### ISSUE TITLE
 Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.bijiben#1]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.Pf38wp9tIYElYlndqRNR5AHaD5%26pid%3D15.1&f=1

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.Qx8pNSw6fNH4oKKeafPz_AHaEA%26pid%3D15.1&f=1

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-02-20 19-32-01](https://user-images.githubusercontent.com/26097419/36453140-ccb37e04-1675-11e8-9fef-9681c4fdf9c5.png)

**Comment by igaldino** [comment]
Oh, I'm sorry for the delay. I'll provide one as soon as possible.

Em 3 de fev de 2018 22:49, "LeandroStanger" <notifications@github.com>
escreveu:

**Comment by nedrichards** [comment]
This is because the screenshot provided in the upstream appdata is now 404: http://py.luyten.fr/Publique/bijiben-notes-scr.png we need to fix that URL upstream.

**Comment by igaldino** [comment]
Fixed in this commit: https://git.gnome.org/browse/bijiben/commit/?id=2b1bf6533a31f77e79966491907912fd097c5533
