### ISSUE TITLE
Out-of-date pacakge

### ISSUE THREAD

**Issue by tapir** [flathub/org.gnome.bijiben#10]
With gnome 3.32, apps from 3.3 looks off due the app menu icon shown in top left corner.

**Comment by igaldino** [comment]
Hi @tapir thanks for your bug report. Yeah, we're working to get a new version, which will be based on org.gnome.Notes and not org.gnome.bijbien anymore (1).
Please follow that up. I'll close this one.
Thanks.
1 - https://github.com/flathub/flathub/pull/937
